### ISSUE TITLE
No information available on meetings

### ISSUE THREAD

**Issue by dfabulich** [web-platform-dx/admin#2]
https://github.com/web-platform-dx/admin/blob/main/charter.md

> Meetings may be restricted to Community Group participants and guests invited by the group chairs, but a public summary or minutes will be made available publicly.

I can't find any meeting minutes here in this repository or in any of the other repositories in https://github.com/web-platform-dx

I have the following questions, which I think, by the charter, ought to be public information, but it doesn't seem to be available:

* Has this community group had any meetings yet?
* Assuming the community group has had a meeting, where are the minutes?
* Is there another meeting planned/scheduled? If so, when is the next meeting?
* When/how would the next meeting be planned or scheduled?

It would be good to have answers to these questions here in a reply to this issue, but I think it's important (and would be much better) for all of this information to be visible in the repo itself.

**Comment by tidoust** [comment]
This repository hosts the charter of the community group. You'll find more info and links on the [WebDX group's home page](https://www.w3.org/community/webdx/), although meetings should indeed be better advertized, and pointer better organized.

> * Has this community group had any meetings yet?

Yes, the group has meetings every other week, currently on Thursdays at 3PM UTC.

> 
> * Assuming the community group has had a meeting, where are the minutes?

The group takes rough minutes in a [public Google doc](https://docs.google.com/document/d/1ree75ImLZjf60lTZ3BhCaLHygxgywr7SBXp-q0xPs8A/edit?usp=sharing)

> * Is there another meeting planned/scheduled? If so, when is the next meeting?

Next meeting is planned on [Thursday 25 May - 3PM UTC](https://www.w3.org/events/meetings/b3e5ee4e-eb23-421d-980e-b2f9cca2b0f8/20230525T150000), open to Community Group participants.

> 
> * When/how would the next meeting be planned or scheduled?

On top of repositories, the group also has a mailing-list, with [public archives](https://lists.w3.org/Archives/Public/public-webdx/). This is where calendar invites are being sent.

> It would be good to have answers to these questions here in a reply to this issue, but I think it's important (and would be much better) for all of this information to be visible in the repo itself.

Yes, will work on it!

**Comment by tidoust** [comment]
WebDX repositories now have READMEs that link back to the [group's home page](https://www.w3.org/community/webdx/) (and not its charter). That home page also now features a [work mode blog post](https://www.w3.org/community/webdx/2023/05/16/webdx-cg-work-mode/) that describes the current workstreams, meeting logistics, and communication channels used by the group. Certainly not perfect but hopefully that makes things clearer!

Closing this issue accordingly. Feel free to re-open or raise further issues as needed!
